//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIProcess.ProfessionsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfessionsServiceReference.IProfessionsService")]
    public interface IProfessionsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessionsService/CreateProfession", ReplyAction="http://tempuri.org/IProfessionsService/CreateProfessionResponse")]
        void CreateProfession(BusinessEntities.Profession profession);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessionsService/CreateProfession", ReplyAction="http://tempuri.org/IProfessionsService/CreateProfessionResponse")]
        System.Threading.Tasks.Task CreateProfessionAsync(BusinessEntities.Profession profession);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessionsService/GetProfessionsSummary", ReplyAction="http://tempuri.org/IProfessionsService/GetProfessionsSummaryResponse")]
        BusinessEntities.Profession[] GetProfessionsSummary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessionsService/GetProfessionsSummary", ReplyAction="http://tempuri.org/IProfessionsService/GetProfessionsSummaryResponse")]
        System.Threading.Tasks.Task<BusinessEntities.Profession[]> GetProfessionsSummaryAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfessionsServiceChannel : UIProcess.ProfessionsServiceReference.IProfessionsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfessionsServiceClient : System.ServiceModel.ClientBase<UIProcess.ProfessionsServiceReference.IProfessionsService>, UIProcess.ProfessionsServiceReference.IProfessionsService {
        
        public ProfessionsServiceClient() {
        }
        
        public ProfessionsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfessionsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfessionsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfessionsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateProfession(BusinessEntities.Profession profession) {
            base.Channel.CreateProfession(profession);
        }
        
        public System.Threading.Tasks.Task CreateProfessionAsync(BusinessEntities.Profession profession) {
            return base.Channel.CreateProfessionAsync(profession);
        }
        
        public BusinessEntities.Profession[] GetProfessionsSummary() {
            return base.Channel.GetProfessionsSummary();
        }
        
        public System.Threading.Tasks.Task<BusinessEntities.Profession[]> GetProfessionsSummaryAsync() {
            return base.Channel.GetProfessionsSummaryAsync();
        }
    }
}
