//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIProcess.ProfessionsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfessionsServiceReference.IProfessionsService")]
    public interface IProfessionsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessionsService/CreateProfession", ReplyAction="http://tempuri.org/IProfessionsService/CreateProfessionResponse")]
        UIProcess.ProfessionsServiceReference.CreateProfessionResponse CreateProfession(UIProcess.ProfessionsServiceReference.CreateProfessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessionsService/CreateProfession", ReplyAction="http://tempuri.org/IProfessionsService/CreateProfessionResponse")]
        System.Threading.Tasks.Task<UIProcess.ProfessionsServiceReference.CreateProfessionResponse> CreateProfessionAsync(UIProcess.ProfessionsServiceReference.CreateProfessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessionsService/FindProfessions", ReplyAction="http://tempuri.org/IProfessionsService/FindProfessionsResponse")]
        UIProcess.ProfessionsServiceReference.FindProfessionsResponse FindProfessions(UIProcess.ProfessionsServiceReference.FindProfessionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessionsService/FindProfessions", ReplyAction="http://tempuri.org/IProfessionsService/FindProfessionsResponse")]
        System.Threading.Tasks.Task<UIProcess.ProfessionsServiceReference.FindProfessionsResponse> FindProfessionsAsync(UIProcess.ProfessionsServiceReference.FindProfessionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateProfession", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateProfessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BusinessEntities.Profession profession;
        
        public CreateProfessionRequest() {
        }
        
        public CreateProfessionRequest(BusinessEntities.Profession profession) {
            this.profession = profession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateProfessionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateProfessionResponse {
        
        public CreateProfessionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindProfessions", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindProfessionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string professionDescription;
        
        public FindProfessionsRequest() {
        }
        
        public FindProfessionsRequest(string professionDescription) {
            this.professionDescription = professionDescription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindProfessionsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindProfessionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BusinessEntities.Profession> FindProfessionsResult;
        
        public FindProfessionsResponse() {
        }
        
        public FindProfessionsResponse(System.Collections.Generic.List<BusinessEntities.Profession> FindProfessionsResult) {
            this.FindProfessionsResult = FindProfessionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfessionsServiceChannel : UIProcess.ProfessionsServiceReference.IProfessionsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfessionsServiceClient : System.ServiceModel.ClientBase<UIProcess.ProfessionsServiceReference.IProfessionsService>, UIProcess.ProfessionsServiceReference.IProfessionsService {
        
        public ProfessionsServiceClient() {
        }
        
        public ProfessionsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfessionsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfessionsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfessionsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UIProcess.ProfessionsServiceReference.CreateProfessionResponse CreateProfession(UIProcess.ProfessionsServiceReference.CreateProfessionRequest request) {
            return base.Channel.CreateProfession(request);
        }
        
        public System.Threading.Tasks.Task<UIProcess.ProfessionsServiceReference.CreateProfessionResponse> CreateProfessionAsync(UIProcess.ProfessionsServiceReference.CreateProfessionRequest request) {
            return base.Channel.CreateProfessionAsync(request);
        }
        
        public UIProcess.ProfessionsServiceReference.FindProfessionsResponse FindProfessions(UIProcess.ProfessionsServiceReference.FindProfessionsRequest request) {
            return base.Channel.FindProfessions(request);
        }
        
        public System.Threading.Tasks.Task<UIProcess.ProfessionsServiceReference.FindProfessionsResponse> FindProfessionsAsync(UIProcess.ProfessionsServiceReference.FindProfessionsRequest request) {
            return base.Channel.FindProfessionsAsync(request);
        }
    }
}
