<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="ProfessionsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Persist Security Info=True;User ID=Developer" SettingsObjectName="LocalDataAccessLayer.Properties.Settings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetAllProfessionsSummary" Method="GetAllProfessionsSummary">
    <ElementType Name="GetAllProfessionsSummaryResult">
      <Column Name="ProfessionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CreateProfession" Method="CreateProfession">
    <Parameter Name="description" Type="System.String" DbType="NVarChar(512)" />
    <Return Type="System.Int32" />
  </Function>
</Database>